help = https://github.com/Bearsampp/modules-untouched/releases/download/xlight-2026.8.9/xlight_help.zip
remote = https://github.com/Bearsampp/modules-untouched/releases/download/xlight-2026.8.9/remote_admin.zip
language = https://github.com/Bearsampp/modules-untouched/releases/download/xlight-2026.8.9/language_en.zip
